version: '3.7'

services:
  # web-app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx.dockerfile
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - net
  gochan:
    build:
      context: .
      dockerfile: ./docker/gochan.dockerfile
    container_name: exachan
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - net
networks:
  net:
    driver: bridge