version: '3.7'

services:
  gochan:
    build:
      context: .
      dockerfile: ./docker/gochan.dockerfile
    container_name: server
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - net
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5433"
    networks:
      - net
networks:
  net:
    driver: bridge