version: '3.7'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./starage.db:/build
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - net
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api:/usr/share/nginx/html/swagger
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      API_URL: swagger/swagger.yml
    container_name: swagger-ui
    networks:
      - net
    depends_on:
      - web-app
networks:
  net:
    driver: bridge