swagger: "2.0"

info:
  title: gochan
  description: API for forum
  version: 1.0.0
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /post/create:
    post:
      description: Create post
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            type: object
            required:
              - text
              - img
              - threadId
            properties:
              text:
                type: string
              img:
                type: string
              threadId:
                type: string
      responses:
        '200':
          description: "Response"
          schema:
            $ref: '#/definitions/responses'
  /thread/create:
    post:
      description: Create thread
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            type: object
            required:
              - text
              - img
              - head
              - passwordHash
            properties:
              text:
                type: string
              img:
                type: string
              head:
                type: string
              passwordHash:
                type: string
      responses:
        '200':
          description: "Response success"
          schema:
            $ref: '#/definitions/createThread'
        '400':
          description: "Response error"
          schema:
            $ref: '#/definitions/responses'
  /thread/login:
    post:
      description: Login in thread
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            type: object
            required:
              - passwordHash
            properties:
              passwordHash:
                type: string
      responses:
        '200':
          description: "Response success"
          schema:
            $ref: '#/definitions/responses'
        '400':
          description: "Response error"
          schema:
            $ref: '#/definitions/responses'


definitions:
  responses:
    type: object
    properties:
      err:
        type: boolean
      message:
        type: string
  createThread:
    type: object
    properties:
      idThread:
        type: integer